// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestartVisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RestartVisualStudioPackageString = "6359da17-6477-4e9c-8e73-7d05ea8a33a1";
        public const string RestartVisualStudioCommandSetString = "4eac4e23-4909-4dac-9d6e-819bdc861480";
        public static Guid RestartVisualStudioPackage = new Guid(RestartVisualStudioPackageString);
        public static Guid RestartVisualStudioCommandSet = new Guid(RestartVisualStudioCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int YannsEssentialsToolbar = 0x4000;
        public const int CodeEditorGroup = 0x0000;
        public const int CodeEditorMenu = 0x0001;
        public const int RestartGroup = 0x0100;
        public const int RestartDropDown = 0x0101;
        public const int RestartCommands = 0x0102;
        public const int RestartNormalCommand = 0x0105;
        public const int RestartElevatedCommand = 0x0106;
    }
}
