// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestartVisualStudio
{
    static class Vsix
    {
        public const string Id = "YD.RestartVisualStudio";
        public const string Name = "Yann's Essentials - Restart Visual Studio";
        public const string Description = "The simplest way of restarting VIsual Studio on demand (normal and elevated).";
        public const string Language = "en-US";
        public const string Version = "0.1.1";
        public const string Author = "Yann Duran";
        public const string Tags = "";
    }
}
