// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestartVisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string YannsEssentialsCommandSetString = "3e73125a-ed32-4e5e-b613-e5371da764aa";
        public static Guid YannsEssentialsCommandSet = new Guid(YannsEssentialsCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeEditorGroup = 0x0000;
        public const int YannsEssentialsToolbar = 0x0100;
        public const int YannsEssentialsMenu = 0x0102;
    }
}
